<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net11.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <IsShipped>true</IsShipped>
    <AssemblyName>CoreWebForms.ConfigurationManager</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="11.0.0-rc.1.26425.128" />
  </ItemGroup>

</Project>
