<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsShipped>true</IsShipped>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>CoreWebForms.SqlClient</AssemblyName>
    <RootNamespace>System.Web</RootNamespace>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebForms\WebForms.csproj" />
  </ItemGroup>

</Project>
